# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/axelilvo/simplertk2b

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/axelilvo/simplertk2b

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axelilvo/simplertk2b/CMakeFiles /home/axelilvo/simplertk2b/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/axelilvo/simplertk2b/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gps

# Build rule for target.
gps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gps
.PHONY : gps

# fast build rule for target.
gps/fast:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/build
.PHONY : gps/fast

#=============================================================================
# Target rules for targets named simplertk2b

# Build rule for target.
simplertk2b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplertk2b
.PHONY : simplertk2b

# fast build rule for target.
simplertk2b/fast:
	$(MAKE) -f CMakeFiles/simplertk2b.dir/build.make CMakeFiles/simplertk2b.dir/build
.PHONY : simplertk2b/fast

gps/ntrip/ntrip.o: gps/ntrip/ntrip.c.o

.PHONY : gps/ntrip/ntrip.o

# target to build an object file
gps/ntrip/ntrip.c.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/ntrip/ntrip.c.o
.PHONY : gps/ntrip/ntrip.c.o

gps/ntrip/ntrip.i: gps/ntrip/ntrip.c.i

.PHONY : gps/ntrip/ntrip.i

# target to preprocess a source file
gps/ntrip/ntrip.c.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/ntrip/ntrip.c.i
.PHONY : gps/ntrip/ntrip.c.i

gps/ntrip/ntrip.s: gps/ntrip/ntrip.c.s

.PHONY : gps/ntrip/ntrip.s

# target to generate assembly for a file
gps/ntrip/ntrip.c.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/ntrip/ntrip.c.s
.PHONY : gps/ntrip/ntrip.c.s

gps/serialcomm/serialComm.o: gps/serialcomm/serialComm.c.o

.PHONY : gps/serialcomm/serialComm.o

# target to build an object file
gps/serialcomm/serialComm.c.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/serialcomm/serialComm.c.o
.PHONY : gps/serialcomm/serialComm.c.o

gps/serialcomm/serialComm.i: gps/serialcomm/serialComm.c.i

.PHONY : gps/serialcomm/serialComm.i

# target to preprocess a source file
gps/serialcomm/serialComm.c.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/serialcomm/serialComm.c.i
.PHONY : gps/serialcomm/serialComm.c.i

gps/serialcomm/serialComm.s: gps/serialcomm/serialComm.c.s

.PHONY : gps/serialcomm/serialComm.s

# target to generate assembly for a file
gps/serialcomm/serialComm.c.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/serialcomm/serialComm.c.s
.PHONY : gps/serialcomm/serialComm.c.s

gps/simplertk2b/gganmealine.o: gps/simplertk2b/gganmealine.cpp.o

.PHONY : gps/simplertk2b/gganmealine.o

# target to build an object file
gps/simplertk2b/gganmealine.cpp.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/gganmealine.cpp.o
.PHONY : gps/simplertk2b/gganmealine.cpp.o

gps/simplertk2b/gganmealine.i: gps/simplertk2b/gganmealine.cpp.i

.PHONY : gps/simplertk2b/gganmealine.i

# target to preprocess a source file
gps/simplertk2b/gganmealine.cpp.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/gganmealine.cpp.i
.PHONY : gps/simplertk2b/gganmealine.cpp.i

gps/simplertk2b/gganmealine.s: gps/simplertk2b/gganmealine.cpp.s

.PHONY : gps/simplertk2b/gganmealine.s

# target to generate assembly for a file
gps/simplertk2b/gganmealine.cpp.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/gganmealine.cpp.s
.PHONY : gps/simplertk2b/gganmealine.cpp.s

gps/simplertk2b/nmealine.o: gps/simplertk2b/nmealine.cpp.o

.PHONY : gps/simplertk2b/nmealine.o

# target to build an object file
gps/simplertk2b/nmealine.cpp.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/nmealine.cpp.o
.PHONY : gps/simplertk2b/nmealine.cpp.o

gps/simplertk2b/nmealine.i: gps/simplertk2b/nmealine.cpp.i

.PHONY : gps/simplertk2b/nmealine.i

# target to preprocess a source file
gps/simplertk2b/nmealine.cpp.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/nmealine.cpp.i
.PHONY : gps/simplertk2b/nmealine.cpp.i

gps/simplertk2b/nmealine.s: gps/simplertk2b/nmealine.cpp.s

.PHONY : gps/simplertk2b/nmealine.s

# target to generate assembly for a file
gps/simplertk2b/nmealine.cpp.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/nmealine.cpp.s
.PHONY : gps/simplertk2b/nmealine.cpp.s

gps/simplertk2b/rmcnmealine.o: gps/simplertk2b/rmcnmealine.cpp.o

.PHONY : gps/simplertk2b/rmcnmealine.o

# target to build an object file
gps/simplertk2b/rmcnmealine.cpp.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/rmcnmealine.cpp.o
.PHONY : gps/simplertk2b/rmcnmealine.cpp.o

gps/simplertk2b/rmcnmealine.i: gps/simplertk2b/rmcnmealine.cpp.i

.PHONY : gps/simplertk2b/rmcnmealine.i

# target to preprocess a source file
gps/simplertk2b/rmcnmealine.cpp.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/rmcnmealine.cpp.i
.PHONY : gps/simplertk2b/rmcnmealine.cpp.i

gps/simplertk2b/rmcnmealine.s: gps/simplertk2b/rmcnmealine.cpp.s

.PHONY : gps/simplertk2b/rmcnmealine.s

# target to generate assembly for a file
gps/simplertk2b/rmcnmealine.cpp.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/rmcnmealine.cpp.s
.PHONY : gps/simplertk2b/rmcnmealine.cpp.s

gps/simplertk2b/simplertk2b.o: gps/simplertk2b/simplertk2b.cpp.o

.PHONY : gps/simplertk2b/simplertk2b.o

# target to build an object file
gps/simplertk2b/simplertk2b.cpp.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/simplertk2b.cpp.o
.PHONY : gps/simplertk2b/simplertk2b.cpp.o

gps/simplertk2b/simplertk2b.i: gps/simplertk2b/simplertk2b.cpp.i

.PHONY : gps/simplertk2b/simplertk2b.i

# target to preprocess a source file
gps/simplertk2b/simplertk2b.cpp.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/simplertk2b.cpp.i
.PHONY : gps/simplertk2b/simplertk2b.cpp.i

gps/simplertk2b/simplertk2b.s: gps/simplertk2b/simplertk2b.cpp.s

.PHONY : gps/simplertk2b/simplertk2b.s

# target to generate assembly for a file
gps/simplertk2b/simplertk2b.cpp.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps/simplertk2b/simplertk2b.cpp.s
.PHONY : gps/simplertk2b/simplertk2b.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/simplertk2b.dir/build.make CMakeFiles/simplertk2b.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/simplertk2b.dir/build.make CMakeFiles/simplertk2b.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/simplertk2b.dir/build.make CMakeFiles/simplertk2b.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gps"
	@echo "... simplertk2b"
	@echo "... gps/ntrip/ntrip.o"
	@echo "... gps/ntrip/ntrip.i"
	@echo "... gps/ntrip/ntrip.s"
	@echo "... gps/serialcomm/serialComm.o"
	@echo "... gps/serialcomm/serialComm.i"
	@echo "... gps/serialcomm/serialComm.s"
	@echo "... gps/simplertk2b/gganmealine.o"
	@echo "... gps/simplertk2b/gganmealine.i"
	@echo "... gps/simplertk2b/gganmealine.s"
	@echo "... gps/simplertk2b/nmealine.o"
	@echo "... gps/simplertk2b/nmealine.i"
	@echo "... gps/simplertk2b/nmealine.s"
	@echo "... gps/simplertk2b/rmcnmealine.o"
	@echo "... gps/simplertk2b/rmcnmealine.i"
	@echo "... gps/simplertk2b/rmcnmealine.s"
	@echo "... gps/simplertk2b/simplertk2b.o"
	@echo "... gps/simplertk2b/simplertk2b.i"
	@echo "... gps/simplertk2b/simplertk2b.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

